refactor: only replace password by star when logging level is debug
tortoise/tortoise-orm pull request #1820
Opened 2024-12-20 03:29 UTC by waketzheng

## Description

When db_url is `'postgres://postgres:postgres@127.0.0.1:5432/db_name'`
logger msg will be: `'po***://po***:po***@127.0.0.1:5432/db_name'`
that looks strange!

## Motivation and Context

## How Has This Been Tested?

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added the changelog accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-12-20 20:01 UTC, henadzit requested changes

2024-12-20 20:01 UTC, henadzit commented on tortoise/__init__.py
> +        if logger.isEnabledFor(logging.DEBUG):
The new code is overly complex. We shouldn't have something that complicated in the main file of the whole project. I would personally have more stars in the debug logs than 5 nested blocks of code to handle it.

2024-12-29 09:02 UTC, abondar approved these changes

2024-12-29 23:07 UTC, henadzit approved these changes

2024-12-30 02:34 UTC, merged